#!/usr/bin/env bash

# function
copy_file() {
  rm -rf \
    ${1}

  cp -RL \
    ${1}_tmp \
    ${1}

  chmod -R 755 \
    ${1}
}

no() {
  yes | sed 's/y/n/g'
}

# Copy writable config
CONFIGS_TO_COPY=(
  ~/.config/VencordDesktop/VencordDesktop
  ~/.config/libreoffice
  ~/.config/background.png
  ~/.config/kitty
  ~/.config/rofi
  ~/.config/waybar
  ~/.local/bin/lockscreen
  ~/.config/hypr/color.conf
)

for CONFIG_PATH in ${CONFIGS_TO_COPY[@]}; do
  copy_file ${CONFIG_PATH}
done

# Copy if not exist
# EDITABLE_CONFIGS_TO_COPY=(
# )

# for CONFIG_PATH in ${EDITABLE_CONFIGS_TO_COPY}; do
#   [[ -f ${CONFIG_PATH} && -d ${CONFIG_PATH} ]] \
#     && copy_file ${CONFIG_PATH}
# done

# Setup no package programs
lvim_install() {
  no | LV_BRANCH='release-1.3/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh)
}

[ ! -d "${HOME}/.config/lvim/" ] \
  && lvim_install
