#!/usr/bin/env bash

# Copy writable config
CONFIGS_TO_COPY=(
  ~/.config/Vencord
  ~/.config/libreoffice
)

for CONFIG_PATH in ${CONFIGS_TO_COPY}; do
  rm -rf \
    ${CONFIG_PATH}

  cp -RL \
    ${CONFIG_PATH}_tmp \
    ${CONFIG_PATH}

  chmod -R 755 \
    ${CONFIG_PATH}
done

# Setup no package programs
SETUP_LIST=(
  (
    [ ! -d "${HOME}/.config/lvim/" ]
    "LV_BRANCH='release-1.3/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh)"
  )
)

for SETUP in ${SETUP_LIST}; do
  if ${SETUP[0]}; then
    ${SETUP[1]}
  fi
done
