#!/usr/bin/env bash

## Author  : Aditya Shakya (adi1090x)
## Github  : @adi1090x
#
## Applets : MPD (music)

# Import Current Theme
source "$HOME"/.config/rofi/applets/shared/theme.bash
theme="$type/$style"

ARGS="--volume=25"

notification(){
	notify-send "Playing now: " "$@" --icon=media-tape
}

# Theme Elements
status="`mpc status`"
if [[ -z "$status" ]]; then
	prompt='Offline'
	mesg="MPD is Offline"
else
	prompt="`mpc -f "%artist%" current`"
	mesg="`mpc -f "%title%" current` :: `mpc status | grep "#" | awk '{print $3}'`"
fi

if [[ ( "$theme" == *'type-1'* ) || ( "$theme" == *'type-3'* ) || ( "$theme" == *'type-5'* ) ]]; then
	list_col='1'
	list_row='6'
elif [[ ( "$theme" == *'type-2'* ) || ( "$theme" == *'type-4'* ) ]]; then
	list_col='6'
	list_row='1'
fi

# Options
layout=`cat ${theme} | grep 'USE_ICON' | cut -d'=' -f2`
option_1=" Lofi Naruto"
option_2=" Lofi Girl"
option_3=" Lofi Animal Crossing"
option_4=" Lofi Zelda"
option_5=" Lofi Anime"
option_6=" Stop"

# Toggle Actions
active=''
urgent=''
# Random
if [[ ${status} == *"random: on"* ]]; then
    [ -n "$active" ] && active+=",5" || active="-a 5"
elif [[ ${status} == *"random: off"* ]]; then
    [ -n "$urgent" ] && urgent+=",5" || urgent="-u 5"
else
    option_6=" Parsing Error"
fi

# Rofi CMD
rofi_cmd() {
	rofi -theme-str "listview {columns: $list_col; lines: $list_row;}" \
		-theme-str 'textbox-prompt-colon {str: "";}' \
		-dmenu \
		-p "$prompt" \
		-mesg "$mesg" \
		${active} ${urgent} \
		-markup-rows \
		-theme ${theme}
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6" | rofi_cmd
}

play_music() {
  notification ${chosen}
	mpv $ARGS --title="radio-mpv" $URL --no-video
}

# Execute Command
run_cmd() {
	if [[ "$1" == '--opt1' ]]; then
		URL="https://youtu.be/dd-bYJk8CtM"
	elif [[ "$1" == '--opt2' ]]; then
		URL="https://youtu.be/jfKfPfyJRdk"
	elif [[ "$1" == '--opt3' ]]; then
		URL="https://youtu.be/MlvPoNMa8ug"
	elif [[ "$1" == '--opt4' ]]; then
		URL="https://youtu.be/kFDJ-zskFhk"
	elif [[ "$1" == '--opt5' ]]; then
		URL="https://youtu.be/OrBOBDeQnwQ"
	fi

  pkill -f radio-mpv
  play_music
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    $option_1)
		run_cmd --opt1
        ;;
    $option_2)
		run_cmd --opt2
        ;;
    $option_3)
		run_cmd --opt3
        ;;
    $option_4)
		run_cmd --opt4
        ;;
    $option_5)
		run_cmd --opt5
        ;;
    $option_6)
		run_cmd --opt6
        ;;
esac
