#!/bin/sh

if ! [ -f $HOME/iso/win10.iso ]; then
    echo -e "Download $HOME/iso/win10.iso\n"

    mkdir -p $HOME/iso
    curl -o $HOME/iso/win10.iso https://download944.mediafire.com/2jobduyv89igkeaq-DfRwcxITTgH0N61Q0vyIj_VE1xujSKCBmuZh120T24M7vaWr1e6I5ige5NwKPqS6ouDXlbIAMb6cCQmZIE4wwI0EO98XG6Z6dikwdGYxxt75dG_U6FSLSBX_Lxc7AFrd6iD6u01imPkiCo00cE4466lc6iE9g/4mmlvw9s1ddjckd/Win10_22H2_French_x64.iso
fi

if ! [ -f $HOME/iso/virtio-win.iso ]; then
    echo -e "Download $HOME/iso/virtio-win.iso\n"
    
    mkdir -p $HOME/iso
    curl -o $HOME/iso/virtio-win.iso https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.229-1/virtio-win-0.1.229.iso
fi

if ! [ -f $HOME/vbios/gpu.rom ]; then
    echo -e "Dump vbios\n"
    
    mkdir -p $HOME/vbios

    PCIEID=03:00.0
    export PATH_TO_ROM=$(sudo find /sys/devices/pci0000:00/ | grep $PCIEID | grep rom)

    sudo echo 1 > $PATH_TO_ROM
    sudo mkdir -p /usr/share/kvm/
    sudo cat $PATH_TO_ROM > /usr/share/kvm/gpu.rom
    sudo echo 0 > $PATH_TO_ROM
fi