#!/usr/bin/env bash

swaylock \
  --screenshots \
  --clock \
  --indicator \
  --indicator-radius 100 \
  --indicator-thickness 7 \
  --effect-blur 7x5 \
  --effect-vignette 0.5:0.5 \
  --ring-color 73B1C3 \
  --key-hl-color 8E93BA \
  --line-color 131219 \
  --inside-color 131219 \
  --separator-color 131219
