#!/usr/bin/env bash

swaylock \
  --screenshots \
  --clock \
  --indicator \
  --indicator-radius 100 \
  --indicator-thickness 7 \
  --effect-blur 7x5 \
  --effect-vignette 0.5:0.5 \
  --ring-color {{ color1 }} \
  --key-hl-color {{ color4 }} \
  --line-color {{ background }} \
  --inside-color {{ background }} \
  --separator-color {{ background }}
