#!/usr/bin/env bash

pkill -f swaybg
pkill -f waybar

cpwrconf
rm -rf ~/.cache
rm -rf ~/.config/wpg/schemes/*
rm -rf ~/.background

BACKGROUNDS=$(ls ~/.config/background/ | cut -d ' ' -f 1)
NUMBERS_OF_BACKGROUNDS=0;

for j in ${BACKGROUNDS}; do
  ((NUMBERS_OF_BACKGROUNDS++));
done;

WALPAPER=$(
  echo ${BACKGROUNDS} | cut -d ' ' -f $((1 + RANDOM % NUMBERS_OF_BACKGROUNDS))
)

ln -s ~/.config/background/${WALPAPER} ~/.background

wal -i ~/.config/background/${WALPAPER}
wpg -a ~/.config/background/${WALPAPER}
wpg -A ${WALPAPER}
wpg -s ${WALPAPER}

source ~/.cache/wal/colors.sh
cp ~/.cache/wal/colors-kitty.conf ~/.config/kitty/colors-kitty.conf

# Replace color with #
FILES=(
  ~/.config/rofi/themes/pywal.rasi
  ~/.config/rofi/applets/type-5/style-3.rasi
  ~/.config/waybar/style.css
)

for FILE in ${FILES[@]}; do
  sed -i "s/{{ background }}/${background}/g" ${FILE}
  sed -i "s/{{ foreground }}/${foreground}/g" ${FILE}
  sed -i "s/{{ color1 }}/${color2}/g" ${FILE}
  sed -i "s/{{ color2 }}/${color1}/g" ${FILE}
  sed -i "s/{{ color3 }}/${color3}/g" ${FILE}
  sed -i "s/{{ color4 }}/${color4}/g" ${FILE}
done

# Replace color without #
background=$(echo ${background} | sed "s/#//g")
foreground=$(echo ${foreground} | sed "s/#//g")
color1=$(echo ${color1} | sed "s/#//g")
color2=$(echo ${color2} | sed "s/#//g")
color3=$(echo ${color3} | sed "s/#//g")
color4=$(echo ${color4} | sed "s/#//g")

FILES=(
  ~/.config/hypr/color.conf
  ~/.local/bin/lockscreen
)

for FILE in ${FILES[@]}; do
  sed -i "s/{{ background }}/${background}/g" ${FILE}
  sed -i "s/{{ foreground }}/${foreground}/g" ${FILE}
  sed -i "s/{{ color1 }}/${color2}/g" ${FILE}
  sed -i "s/{{ color2 }}/${color1}/g" ${FILE}
  sed -i "s/{{ color3 }}/${color3}/g" ${FILE}
  sed -i "s/{{ color4 }}/${color4}/g" ${FILE}
done

hyprctl reload
swaybg -m fill -i ~/.config/background/${WALPAPER} &
waybar &
