#!/usr/bin/env bash

rm -rf \
  ~/.config/VencordDesktop/VencordDesktop

cp -RL \
  ~/.config/VencordDesktop/VencordDesktopTmp \
  ~/.config/VencordDesktop/VencordDesktop

chmod -R 755 \
  ~/.config/VencordDesktop/VencordDesktop
